table onlineRetailData
	lineageTag: 27191493-e2bf-4c0a-9d13-89090f4196e4

	measure 'Total Revenue' = SUM('onlineRetailData'[TotalPrice])
		lineageTag: 084fd778-79b8-4e7e-888c-a169f02c227d

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total Customers' = DISTINCTCOUNT(('onlineRetailData'[CustomerID]))
		formatString: 0
		lineageTag: ef9c5071-b5b5-4060-bb88-1a1452ddd126

	measure 'Average Order Value' = DIVIDE([Total Revenue], DISTINCTCOUNT('onlineRetailData'[InvoiceNo]))
		lineageTag: 9ff84bb9-9561-40a9-bccb-d488f01ae33a

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Revenue Growth' =
			
			VAR CurrentRevenue=[Total Revenue]
			VAR PreviousRevenue=CALCULATE([Total Revenue], PREVIOUSMONTH('onlineRetailData'[InvoiceDate]))
			RETURN DIVIDE(CurrentRevenue-PreviousRevenue, PreviousRevenue)
		lineageTag: 34b4d217-81b9-4680-8388-8a3c2f77ee3f

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total Orders' = DISTINCTCOUNT('onlineRetailData'[InvoiceNo])
		formatString: 0
		lineageTag: f5bca9b3-4abb-4624-b730-ec18c08026d7

	measure 'Customer Segment' =
			
			VAR LastOrderDate=MAX('onlineRetailData'[InvoiceDate])
			VAR MaxDatasetDate = CALCULATE(MAX('onlineRetailData'[InvoiceDate]), ALL('onlineRetailData'))
			VAR DaySince=DATEDIFF(LastOrderDate, MaxDatasetDate, DAY)
			RETURN
			    IF(DaySince <=30, "Active",
			    IF(DaySince >=90, "At Risk",
			    "Churned"))
		lineageTag: 7c0b6741-102a-48af-84ec-03b318095b4b

	measure 'Purcahse Frequency' = DISTINCTCOUNT('onlineRetailData'[InvoiceNo])
		formatString: 0
		lineageTag: d4c7f65a-648b-4dd8-a61f-7cdac9229f17

	measure PurchaseFrequencyColumn = CALCULATE(DISTINCTCOUNT('onlineRetailData'[InvoiceNo]), ALLEXCEPT('onlineRetailData', 'onlineRetailData'[CustomerID]))
		formatString: 0
		lineageTag: f0c48db6-b45d-4e41-b2ee-14aae665d116

	measure Measure = HOUR('onlineRetailData'[InvoiceDate])
		lineageTag: 535800ee-f9cb-4ec3-b9e4-a45058aff91f

	measure HourOfOrder
		lineageTag: b2a21ce2-3390-4faf-a1da-028220607eff

	column InvoiceNo
		dataType: int64
		formatString: 0
		lineageTag: 1b01899d-1f75-4b6d-8eb5-5e575e9ada53
		summarizeBy: sum
		sourceColumn: InvoiceNo

		annotation SummarizationSetBy = Automatic

	column StockCode
		dataType: string
		lineageTag: 67b087a4-c246-40b0-8be5-d34fb548a360
		summarizeBy: none
		sourceColumn: StockCode

		annotation SummarizationSetBy = Automatic

	column Description
		dataType: string
		lineageTag: 43ca6848-e64a-4ce0-a486-8568d86e8e9b
		summarizeBy: none
		sourceColumn: Description

		annotation SummarizationSetBy = Automatic

	column Quantity
		dataType: int64
		formatString: 0
		lineageTag: ff180b92-41d7-46c9-9604-09991e13c642
		summarizeBy: sum
		sourceColumn: Quantity

		annotation SummarizationSetBy = Automatic

	column InvoiceDate
		dataType: dateTime
		formatString: General Date
		lineageTag: a158d63b-a4e6-49b4-a875-794148c1b335
		summarizeBy: none
		sourceColumn: InvoiceDate

		variation Variation
			isDefault
			relationship: 64db5745-2ff8-4e84-b17c-ed53f48e37dd
			defaultHierarchy: LocalDateTable_6d997f37-b315-4c8a-8596-f5f4349506a7.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column UnitPrice
		dataType: double
		lineageTag: d513a6d0-2b66-4412-a469-687c95627bb2
		summarizeBy: sum
		sourceColumn: UnitPrice

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column CustomerID
		dataType: int64
		formatString: 0
		lineageTag: 5c93cc74-d8b6-46ae-a6b4-d28e9314f92e
		summarizeBy: count
		sourceColumn: CustomerID

		annotation SummarizationSetBy = Automatic

	column Country
		dataType: string
		lineageTag: 90aa08ba-9bfd-4cd6-a200-a55798f0de3f
		summarizeBy: none
		sourceColumn: Country

		annotation SummarizationSetBy = Automatic

	column is_returned
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 2a62eb53-f7dd-448f-85bf-8454152e0900
		summarizeBy: none
		sourceColumn: is_returned

		annotation SummarizationSetBy = Automatic

	column TotalPrice
		dataType: double
		lineageTag: 21e312f7-154d-42f0-9061-7d1efeaa1c66
		summarizeBy: sum
		sourceColumn: TotalPrice

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Year
		dataType: int64
		formatString: 0
		lineageTag: 029d76e4-5232-4d04-8c6e-ce59b7d993ba
		summarizeBy: sum
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		formatString: 0
		lineageTag: 0d6bb7c8-557a-439b-801d-a0181d51ca77
		summarizeBy: sum
		sourceColumn: Month

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: string
		lineageTag: 5827b5df-f3f5-46f4-b22e-ccea91ecb03a
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column HourOfOrderCol = HOUR('onlineRetailData'[InvoiceDate])
		formatString: 0
		lineageTag: c00b0ae3-9d81-4857-969e-71bce1341e4f
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	partition onlineRetailData = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\fatim\Desktop\GITHUB REPO\Data_Analysis\Data_Analysis\E-commerce Customer Behavior Analysis\onlineRetailData.csv"),[Delimiter=",", Columns=13, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"InvoiceNo", Int64.Type}, {"StockCode", type text}, {"Description", type text}, {"Quantity", Int64.Type}, {"InvoiceDate", type datetime}, {"UnitPrice", type number}, {"CustomerID", Int64.Type}, {"Country", type text}, {"is_returned", type logical}, {"TotalPrice", type number}, {"Year", Int64.Type}, {"Month", Int64.Type}, {"DayOfWeek", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

